"""
AutoShorts Modules Package

Contains reusable modules for AutoShorts video generation.
"""

from .config import (
    API_KEY,
    API_TIMEOUT_IMAGE,
    API_TIMEOUT_SEARCH,
    API_TIMEOUT_TEXT,
    API_URL,
    AUDIO_CODEC,
    BG_MODE,
    BLUR_RADIUS,
    BOTTOM_MARGIN,
    COLOR_HIGHLIGHT,
    COLOR_STROKE,
    COLOR_TEXT,
    CROSSFADE_TIME,
    DEFAULT_FONT,
    ENCODING_CRF,
    ENCODING_PRESET,
    ENCODING_THREADS,
    FALLBACK_FONTS,
    FFPROBE_TIMEOUT,
    FONT_SIZE,
    IMAGE_BOUNCE_INTERVAL,
    IMAGE_CACHE_DIR,
    IMAGE_FADE_IN_TIME,
    IMAGE_FADE_OUT_TIME,
    IMAGE_OVERLAY_DURATION,
    IMG_URL,
    JUMPCUT_SEG_DUR,
    LINE_SPACING,
    MAX_CHARS_PER_LINE,
    MAX_VIDEO_CUT_DURATION,
    MAX_VIDEO_DURATION,
    MAX_ZOOM_VALUE,
    MIN_VIDEO_DURATION,
    MODEL_IMAGE,
    MODEL_TEXT,
    OUTPUT_DIR,
    SCENE_DURATION_SECONDS,
    START_FADE,
    STROKE_WIDTH,
    SUBTITLE_MODE,
    SUBTITLE_START_Y_RATIO,
    TEMP_DIR_PREFIX,
    TTS_RATE,
    VIDEO_CODEC,
    VIDEO_DURATION_SECONDS,
    VIDEO_FPS,
    VIDEO_HEIGHT,
    VIDEO_WIDTH,
    VOICE,
    YOUTUBE_FORMAT,
    YOUTUBE_MAX_HEIGHT,
)
from .logging_system import Colors, log
from .script_generator import ScriptGenerator
from .subtitle_system import SubtitleGenerator, SubtitleRenderer, SubtitleSystem
from .tts_system import TTSSystem
from .utils import (
    clean_temp_files,
    create_temp_dir,
    get_system_font,
    setup_directories,
    shutdown_computer,
)
from .video_background import VideoBackgroundManager
from .video_compositor import VideoCompositor

__all__ = [
    "API_KEY",
    "API_TIMEOUT_IMAGE",
    "API_TIMEOUT_SEARCH",
    "API_TIMEOUT_TEXT",
    "API_URL",
    "AUDIO_CODEC",
    "BG_MODE",
    "BLUR_RADIUS",
    "BOTTOM_MARGIN",
    "COLOR_HIGHLIGHT",
    "COLOR_STROKE",
    "COLOR_TEXT",
    "CROSSFADE_TIME",
    "DEFAULT_FONT",
    "ENCODING_CRF",
    "ENCODING_PRESET",
    "ENCODING_THREADS",
    "FALLBACK_FONTS",
    "FFPROBE_TIMEOUT",
    "FONT_SIZE",
    "IMG_URL",
    "IMAGE_CACHE_DIR",
    "IMAGE_FADE_IN_TIME",
    "IMAGE_FADE_OUT_TIME",
    "IMAGE_OVERLAY_DURATION",
    "IMAGE_BOUNCE_INTERVAL",
    "JUMPCUT_SEG_DUR",
    "LINE_SPACING",
    "MAX_CHARS_PER_LINE",
    "MAX_VIDEO_CUT_DURATION",
    "MAX_VIDEO_DURATION",
    "MAX_ZOOM_VALUE",
    "MIN_VIDEO_DURATION",
    "MODEL_IMAGE",
    "MODEL_TEXT",
    "OUTPUT_DIR",
    "SCENE_DURATION_SECONDS",
    "START_FADE",
    "STROKE_WIDTH",
    "SUBTITLE_MODE",
    "SUBTITLE_START_Y_RATIO",
    "TEMP_DIR_PREFIX",
    "TTS_RATE",
    "VIDEO_CODEC",
    "VIDEO_DURATION_SECONDS",
    "VIDEO_FPS",
    "VIDEO_HEIGHT",
    "VIDEO_WIDTH",
    "VOICE",
    "YOUTUBE_FORMAT",
    "YOUTUBE_MAX_HEIGHT",
    "SubtitleSystem",
    "SubtitleGenerator",
    "SubtitleRenderer",
    "log",
    "Colors",
    "ScriptGenerator",
    "TTSSystem",
    "VideoBackgroundManager",
    "VideoCompositor",
    "setup_directories",
    "create_temp_dir",
    "clean_temp_files",
    "get_system_font",
    "get_video_duration",
    "safe_filename",
    "ensure_dir_exists",
    "get_file_size_mb",
    "shutdown_computer",
]
